services:
  db:
    container_name: mongodb_trello_clone_api
    image: mongo:7.0
    ports:
      - 27017:27017
    volumes:
      - trello_clone_api_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  
  mongo_express:
    container_name: mongo_express_trello_clone_api
    image: mongo-express:1.0.2
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:27017/
      ME_CONFIG_BASICAUTH: false
  
  api:
    container_name: api_trello_clone_api
    image: trello-clone-api:latest
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      MONGO_URL: mongodb://db:27017/
      MONGO_USERNAME : ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      ENV: PRO
      API_PORT: ${API_PORT} 

volumes:
  trello_clone_api_volume:
    external: false